# Generated by Django 4.1.1 on 2022-09-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=200)),
                ('Age', models.CharField(max_length=30)),
                ('salary', models.CharField(max_length=16)),
            ],
        ),
    ]
